apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-api-proxy.fullname" . }}-certs
  labels:
    {{- include "k8s-api-proxy.labels" . | nindent 4 }}
data:
  ca.crt: {{ .Values.mTLS.caCert }}
  server.crt: {{ .Values.mTLS.serverCert }}
  server.key: {{ .Values.mTLS.serverKey }}
