{{- if ne .Values.kubeConfig "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-api-proxy.fullname" . }}-kubeconfig
  labels:
    {{- include "k8s-api-proxy.labels" . | nindent 4 }}
data:
  config: {{ .Values.kubeConfig }}
{{- end -}}
